### ISSUE TITLE
May I ask whether your method is the realization of the paper "Temporal pattern attention for multivariate time series forecasting"?

### ISSUE THREAD

**Issue by iorange-77** [Sanyam-Mehta/TPA-LSTM-PyTorch#1]
May I ask whether your method is the realization of the paper "Temporal pattern attention for multivariate time series forecasting"? If yes, then in the convolutional layer constructed by nn.Conv2d, the convolution kernel size is ”kernel_size=(self.ck, self.hidden_state_features)“, shouldn't it be 1*window_length?

**Comment by Sanyam-Mehta** [comment]
Hi,

The answer to your first question is yes.
Regarding the second part, as you might see it from the code, the values of ck can be passed as an argument. I have tried to write a generic code so that parameters can be changed using arguments.
I hope this clears your doubt. I am closing this issue for now, reopen it if you still have questions.
